### ISSUE TITLE
Ontology Browser: indicate somehow where  selected terms are in the tree on the left panel

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2538] opened 2020-05-21 12:23 UTC
when reopening the ontology browser from a query, we should have a way to locate the previously selected term in the tree on the left panel

![image](https://user-images.githubusercontent.com/1181124/82558738-51be7200-9b3c-11ea-94c6-03bef3e502f1.png)

**Comment by denis-crsj** [comment] 2020-05-21 12:33
Closing issue. Duplicate of #2516

**Closed** 2020-05-21 12:34 UTC
