### ISSUE TITLE
Query Builder: Blank queries behavior when adding combinations

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1261] opened 2019-02-27 21:54 UTC
If the user selects "Start a new query", a blank query row is added.  Now if they change their mind and want to combine queries for their next query - there is a blank row in between.

Expected behaviour: If there is a blank query thats already exists at the **bottom of the list**, that query row should be the NEXT USED row.  For example, if the user has a blank row then makes a combination query, add the combination to that blank one.

![screen shot 2019-02-27 at 4 53 38 pm](https://user-images.githubusercontent.com/18424138/53525844-b2cdd600-3ab0-11e9-90fd-463f8e910801.png)

Note: if the user deletes all values from a query within the middle of the list (i.e. not the last query), leave that query row blank for them to add other values to. 
This one is hard to explain, ask Kim or Rosi for a demo

**Comment by hlminh2000** [comment] 2019-03-12 15:06
duplicate of #1255 ? :)

**Comment by kcullion** [comment] 2019-03-12 15:17
@hlminh2000 this is a bit different..can I show you?

**Comment by kcullion** [comment] 2019-03-12 15:21
@hlminh2000 here's a video...the combination should be put in the blank query:
https://drive.google.com/file/d/1soCcR4bj31q_LYB7nQmnrZXDozrwasxZ/view

**Comment by kcullion** [comment] 2019-03-12 15:22
@rosibaj @hlminh2000 now that we are renaming the queries to Q1, Q2...I still think this is the expected behaviour...do you?
(re: https://github.com/kids-first/kf-portal-ui/issues/1300)

**Comment by aalex** [comment] 2019-07-10 14:40
See also #1458 - they are similar

**Closed** 2020-05-12 20:43 UTC
Labels: enhancement
