### ISSUE TITLE
The Virtual Study dropdown is not populated when you navigate back to Explore Data

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1417] opened 2019-03-25 17:38 UTC
When a user "loads" a saved virtual study, then navigates **back** to the Explore data, the queries are pre-loaded but the virtual study name is not. 

![image](https://user-images.githubusercontent.com/15824252/54941387-1659f080-4f03-11e9-99dc-9a9cb65b6bd9.png)
![image](https://user-images.githubusercontent.com/15824252/54941388-1823b400-4f03-11e9-9660-f0932621120b.png)

**Comment by nyanofthemoon** [comment] 2019-04-03 20:08
Not a quick win because the component is re-rendered due to props being changed and passed down by the parent components.

src/components/CohortBuilder/index.js

![debug.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/cd2a7465-f7d9-496e-8cfb-16b182fc3c03)

**Comment by aalex** [comment] 2019-07-10 14:35
Duplicate of #1705 - fixed.

**Closed by aalex** 2019-07-10 14:35 UTC
Labels: blocked, bug, duplicate, groomed
