### ISSUE TITLE
Participant Table: Know which column is sortable

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1495] opened 2019-03-28 17:57 UTC
As a user, we should know which column is sortable.

Note that : Columns with multiple values should not be sortable. (see #1572)

## Acceptance
- let's not sort by number of files
- Know which column is sortable, with some visual insight that it is. 
  - the cursor becomes a pointing hand when we mouse over it
  - There is a line above or below the cell when sorted, like in the file table

## Screenshots
Here is a screenshot of the title cell of a sortable column in the file table.
![screenshot_2019-04-10_10-53-24_sortable.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/263deb93-f7e4-4e6c-bd68-2abc9b6236a1)

**Comment by aalex** [comment] 2019-04-11 22:20
It was estimated with 5 points, but since multiple-value columns are not going to be sortable, I removed the estimate.

**Comment by aalex** [comment] 2019-04-12 19:31
The column that is left in the description for this issue can potentially have multiple values. We should then leave it unsortable, and close this issue. (according to some recent decisions that were made)

**Comment by jberube** [comment] 2019-04-12 19:52
This would make that an official dup of #1572

**Comment by aalex** [comment] 2019-04-12 20:15
It really now is a duplicate of #1572, so I will close this one.

**Closed by aalex** 2019-04-12 20:15 UTC
Labels: enhancement, question
