### ISSUE TITLE
Bug: Footer in cohort builder

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1226] opened 2019-02-20 18:59 UTC
The footer should be fixed to the bottom of the screen (like in the dashboard).

<img width="1615" alt="screen shot 2019-02-20 at 12 40 09 pm" src="https://user-images.githubusercontent.com/18424138/53116899-ba710600-3517-11e9-8430-9ee5d0ed9833.png">

<img width="1615" alt="screen shot 2019-02-26 at 2 30 20 pm" src="https://user-images.githubusercontent.com/15824252/53440743-429d5280-39d3-11e9-8f86-8dbcd0d8de36.png">

**Comment by rosibaj** [comment] 2019-02-25 21:37
@kcullion are you still able to reproduce this on your monitor size?

**Comment by kcullion** [comment] 2019-02-25 21:40
@rosibaj yes I still see it on my monitor (the space below the footer)

![screen shot 2019-02-25 at 4 39 16 pm](https://user-images.githubusercontent.com/18424138/53370548-fd6a1980-391b-11e9-9298-0d60d4b1d1f6.png)

**Comment by rosibaj** [comment] 2019-02-28 23:14
@kcullion Can you QA this one on your screen size?

**Comment by kcullion** [comment] 2019-03-04 14:30
@rosibaj , @jaouad-benassila I still see space under the footer.  It seems ok on the dashboard though (stuck to the bottom of the screen)
![screen shot 2019-03-04 at 9 27 21 am](https://user-images.githubusercontent.com/18424138/53739598-24ff3b80-3e60-11e9-8e62-9211dcfacdb7.png)

**Comment by jaouad-benassila** [comment] 2019-03-04 16:09
@kcullion , @rosibaj it works for me and I can't reproduce it
![footer](https://user-images.githubusercontent.com/47750690/53745851-df496f80-3e6d-11e9-8b69-a2ef8327fcc1.png)

**Comment by kcullion** [comment] 2019-03-04 16:12
@jaouad-benassila does anyone there have a large monitor?
@rosibaj should we ask @ciaranschutte to look at this since I sit by him and we can test easily?

**Comment by kcullion** [comment] 2019-03-04 16:16
@jaouad-benassila @ciaranschutte does it have something to do with the treatment of the div just above the footer? or with positioning? 

They are treated differently when I inspect...

![screen shot 2019-03-04 at 11 15 17 am](https://user-images.githubusercontent.com/18424138/53746355-018fbd00-3e6f-11e9-9c39-bf1bdc100024.png)
![screen shot 2019-03-04 at 11 15 37 am](https://user-images.githubusercontent.com/18424138/53746356-018fbd00-3e6f-11e9-91c2-ea910fc7ee7d.png)

**Comment by ciaranschutte** [comment] 2019-03-04 16:37
I need to finish up the filebreakdown ticket i'm on but I can take a look at this after :)

**Comment by rosibaj** [comment] 2019-03-04 16:38
@ciaranschutte that sounds fine - @jaouad-benassila i will reassign this to Ciaran for later!

**Comment by ciaranschutte** [comment] 2019-03-04 18:39
For this style we just use the default `Page` wrapper component.
So in `App.js` no need to pass a `WrapperComponent`

Also to test different screen sizes on a small monitor you can go into Chrome dev tools and click the `Device Toolbar` to simulate different screen sizes.

**Closed** 2019-03-05 21:35 UTC
Labels: SP:2, bug
