### ISSUE TITLE
Participant page: Add a table of the phenotypes

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1857] opened 2019-06-25 21:55 UTC
As a user, I want to be able to view a page about a participant. It needs to contain their phenotypes.

The table of phenotypes is currently missing. This is due to the information being missing in the results retrieved from the participant-centric index. See the dependency of this issue.

## Acceptance criteria
- Display the table of phenotypes for a user, as specified in #963

## Technical details
- The phenotypes is missing from the participant-centric index.
- We might be able to query directly the data service from the front-end in a near future.

@Velythyl put more details in a comment below about why this is not currently possible.

**Comment by Velythyl** [comment] 2019-06-26 14:47
It's currently not possible to do because when we query a participant its phenotypes are simply not in the results. 

One also notices that the phenotype field in graphql is named "phenotype" whereas all other fields that can have multiple results are plural. In other words, diagnoses is plural and when we query it it returns an array of diagnosis ("hits edges node"). Phenotype should logically return an array of phenotypes, but the graphql query directly asks for the phenotype's data, without an "hits edges node" pattern.

I have the feeling that the ETL is broken for those. I think the file explorer works with phenotypes because it asks them relating to the files, not the participants.

**Comment by jberube** [comment] 2019-08-05 13:58
Duplicate of #1953 , closing

**Closed by jberube** 2019-08-05 13:58 UTC
Labels: ui
