### ISSUE TITLE
The last four columns of the file repository are empty

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1424] opened 2019-03-25 18:51 UTC
In the table of the file repository, when one enables the last four columns, there should be some data. Instead, they are empty.

(web browser: Firefox 66.0.1 (64 bit) for Ubuntu)

![image10](https://user-images.githubusercontent.com/293677/54945967-781f5800-4f0d-11e9-971f-36aab1506ee8.png)

To reproduce: 
- Navigate to https://kf-vr-portal.netlify.com/search/file
- Click on the "Columns" drop-down menu in the top-right area of the window.
- Check the last four items: "Experimental strategies", "Instrument Models", "Is Paired End", "Platforms"

There should be some contents in those columns, but there is none. (Click on the ID of one of these files in order to verify that there really is some data in those fields - for example, the field "Experimental strategy" or a CRAM file should be filled with some info, such as "WGS")

**Comment by rosibaj** [comment] 2019-03-29 01:36
These columns have been removed from selection for the columns.

Originally, these were located directly on file in the model, but these were removed from the source model.  they can now be found on the nested object `file.sequencing_experiments`.  If you want to add these back, it can be done in Arranger admin section easily. 

I am closing this issue as it is not a bug that exists any longer as the blank fields have been removed from the mapping & model.

**Closed by rosibaj** 2019-03-29 01:36 UTC
Labels: bug
