### ISSUE TITLE
Connection to Ego fails at login with Google

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1618] opened 2019-04-18 16:03 UTC
When trying to log in with Google, an error message consitently happens for a user. There is an error message

## Report details
Description: When I’m already logged in with Google its immediate. If I incognito I can click “Connect with Google” but once I sign in there it goes back to this

Users for which it happens:
- zflamig@uchicago.edu (systematically each time) - Chrome and Mac OS X

The error message is: "Connection to Ego failed, you may need to visithttps://ego.kids-first.ioin a new tab and accept the warning" (spelled incorrectly)

## Screenshot
![Screen Shot 2019-04-18 at 11.29.07 AM.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/d779ff87-469d-406b-8f2b-153c9fdbd47f)

**Comment by aalex** [comment] 2019-04-18 17:52
<img width="1666" alt="Screen Shot 2019-04-18 at 1 29 50 PM" src="https://user-images.githubusercontent.com/293677/56380843-3bc7da80-61e1-11e9-97b8-edad4512f1b5.png">

**Comment by jecos** [comment] 2019-04-23 15:24
@aalex I think we can close this one, the user confirmed the issue was due to internal network restrictions.

**Comment by steptek** [comment] 2019-05-02 20:12
For this specific case, it needs to be able to reproduce it with the google account, otherwise, it's not a general issue which should be impacting other users

**Closed** 2020-01-07 21:41 UTC
Labels: backend, bug, question
