### ISSUE TITLE
Update data version API in prod

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1930] opened 2019-07-10 15:02 UTC
As a user, I need to know what data version the portal is serving me.

# Acceptance criteria
- [x] Set the env var, as details below, so that the data version is dynamically updated on the portal.
- [ ] It should make the value shown to the user dynamic.

## Technical details
- The env REACT_APP_DATA_VERSION_API must point to the endpoint.
- The value in our QA environment, for that var is currently https://kf-release-coord-qa.kids-first.io/releases but should be changed to http://kf-release-coord-qa.kidsfirstdrc.org/releases
- The correct value for the prod should be https://kf-release-coord.kidsfirstdrc.org/releases
- See also #1737 

## Screnshots
![image](https://user-images.githubusercontent.com/293677/60980359-54d4b900-a302-11e9-930e-282985d8bdf7.png)

**Comment by aalex** [comment] 2019-07-10 15:42
Done.

There was an old disabled env var in the prod env:

![image](https://user-images.githubusercontent.com/293677/60983387-d67b1580-a307-11e9-8504-7f450c825ce7.png)

**Comment by aalex** [comment] 2019-07-11 15:29
I've updated the value in prod's Netlify, and we have deployed the portal in prod, but the value seems to be not updated. 

![image](https://user-images.githubusercontent.com/293677/61064107-2670df80-a3cf-11e9-80bc-f352a633a96c.png)

**Comment by aalex** [comment] 2019-07-11 19:52
If we set the value of the 'content-type' field to ‘application/json’ in the HTTP header, it might make sure that the Django REST frameworks answers with the contents in the right MIME type.

**Comment by aalex** [comment] 2019-07-11 19:53
`curl -H "Content-Type: application/json" https://kf-release-coord-qa.kidsfirstdrc.org/releases`

**Comment by jberube** [comment] 2019-08-22 19:47
Duplicate of #839

**Closed by jberube** 2019-08-22 19:47 UTC
Labels: backend, task
