### ISSUE TITLE
Cohort builder: The "New" button should be enabled, when a virtual study is open

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1830] opened 2019-06-12 21:15 UTC
As a user, I expect the "New" button should be enabled, when a virtual study is open, so that I can start a new series of search queries from scratch.

## How to reproduce
- Open a saved virtual study **by pasting** its URL in the browser's address bar.
- In the cohort builder, the "New" button should be enabled.

Instead, the "New" button is not enabled.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/2b31006b-18f1-4e3e-b9ce-3460528e653d)

**Comment by jberube** [comment] 2019-06-14 18:54
Can't reproduce.

@aalex provide precise reproduction procedure or close.

**Comment by jberube** [comment] 2019-06-17 13:32
@aalex can we close this one?

**Comment by aalex** [comment] 2019-06-20 15:39
I can still reproduce it: I've observed it yesterday. Let me improve its description.

**Comment by aalex** [comment] 2019-06-20 17:16
I can still reproduce it. Did you try pasting a URL in the address bar?

**Comment by jberube** [comment] 2019-06-20 19:24
Yes.

**Comment by jberube** [comment] 2019-06-20 19:25
Which environment?

**Comment by aalex** [comment] 2019-06-28 21:13
Julien is asking for more info about this bug, so I am moving it to the side, for now.

**Comment by jberube** [comment] 2019-07-02 21:51
Finally could reproduce : looks like @@INIT event is never triggered.

**Comment by aalex** [comment] 2019-07-04 20:04
(QA) It seems like I can still reproduce the bug.

![image](https://user-images.githubusercontent.com/293677/60686199-6a1a9500-9e75-11e9-887b-01a74226aa16.png)

**Comment by aalex** [comment] 2019-07-08 20:21
Unfortunatlely, this issue is still happening in QA. I need to come up with many different ways to reproduce it. Please ask me if you want to start working on fixes for this bug, meanwhile.

**Comment by aalex** [comment] 2019-07-09 16:07
Here is one way to reproduce the bug. It is still almost exactly the steps described in the original ticket.

## Steps to reproduce
- Delete all your virtual studies.
- Open a new tab at https://kf-qa.netlify.com/explore
- Add search query terms.
- Save a virtual study.
- Copy the URL.
- Open a new tab with that URL.
- The New button is disabled. It should not.

**Closed** 2019-07-11 15:05 UTC
Labels: bug
