### ISSUE TITLE
Improve manifest ID upload UI

### ISSUE THREAD

**Issue by hlminh2000** [kids-first/kf-portal-ui#857] opened 2018-10-17 14:51 UTC
continuation of  #811

Functional specifications:
- When searching participant/biospecimen id - the user should only find the single participant/biospecimen ids - when they click on that dropdown value, the table refreshes to find all files associated with that participant or biospecimen.

**Mockups:**
- Change the title of the modal depending on what the user chooses to upload. EG. if the user clicks the "upload list of ids" button for biospecimens, then the modal title should be "Upload a list of Biospecimen Identifiers"

When the user uploads/inserts a list of IDs, instead of the query result saying "File ID is (Uploaded List)"

**Comment by rosibaj** [comment] 2018-11-02 16:00
Closing as duplicate

**Closed by rosibaj** 2018-11-02 16:00 UTC
Labels: SP:3, wontfix

**Comment by Fgerthoffert** [comment] 2018-11-02 18:33
Duplicate of: https://github.com/kids-first/kf-portal-ui/issues/902
